# GPT-2 Fine-tuning Configuration

model:
  name: "gpt2"
  save_path: "models/"
  cache_dir: "models/cache/"
  
data:
  train_file: "data/train_data.json"
  eval_file: "data/eval_data.json"
  max_length: 512
  train_test_split: 0.1
  
# Training Configuration
training:
  output_dir: "outputs/"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 2
  learning_rate: 0.00005  # 5e-5 written as decimal to avoid YAML parsing issues
  weight_decay: 0.01
  warmup_steps: 100
  logging_steps: 10
  eval_steps: 100
  save_steps: 500
  save_total_limit: 3
  eval_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  
# Device Configuration
device:
  use_mps: true  # Use Apple Silicon GPU if available
  use_cuda: false  # Set to true for NVIDIA GPUs
  
# Generation Configuration
generation:
  max_new_tokens: 100
  temperature: 0.7
  do_sample: true
  
# Logging Configuration
logging:
  use_wandb: false
  project_name: "gpt2-finetuning"
  run_name: "gpt2-custom"
  log_level: "INFO"
